name: Code Guardian CI

permissions: read-all|write-all
on: [workflow_dispatch, push]

jobs:
  code-guardian-ci:
    runs-on: ubuntu-latest
    name: Execute Code Guardian CI
    steps:
      - name: Code Guardian CI
        uses: ErnaneJ/code-guardian-ci@e-deploy
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: 1
          token_g: "${{ secrets.GITHUB_TOKEN }}"
          token_oia: "teste"
